name: Conditionally Patch New Release
on:
  workflow_dispatch:
  schedule:
    - cron: "00 0 * * *"

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.getFennec.outputs.build_version }}
      build_needed: ${{ steps.compare.outputs.build_needed }}
    steps:
      - name: Get latest GitHub release tag
        id: getLatest
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          latest_tag=$(gh release view --repo ${{ github.repository }} --json tagName -q ".tagName" 2>/dev/null || echo "")
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
      
      - name: Get latest Fennec release version
        id: getFennec
        run: |
          version=$(curl -s https://f-droid.org/repo/index-v1.json | jq -r '.packages."org.mozilla.fennec_fdroid" | map(select(any(.nativecode[]; . == "arm64-v8a"))) | max_by(.versionCode) | .versionName + "-" + (.versionCode | tostring)')
          echo "build_version=$version" >> $GITHUB_OUTPUT
      
      - name: Check if latest version was already built
        id: compare
        run: |
          if [ "$LATEST_TAG" == "${{ steps.getFennec.outputs.build_version }}" ]; then
            echo "Latest version already built and released."
            echo "build_needed=false" >> $GITHUB_OUTPUT
          else
            echo "New version detected. Triggering build."
            echo "build_needed=true" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check
    if: needs.check.outputs.build_needed == 'true'
    runs-on: ubuntu-latest
    env:
      BUILD_VERSION: ${{ needs.check.outputs.build_version }}
    steps:
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y wget apktool zipalign apksigner
      
      - name: Check out repository code
        uses: actions/checkout@v5
      
      - name: Run build script and sign apk
        env:
          KEY_PASS: ${{ secrets.KEYSTORE_PASSPHRASE }}
        run: |
          chmod +x ./build.sh
          ./build.sh
          echo "${{ secrets.KEYSTORE }}" | base64 -di > keystore.jks
          apksigner sign --ks keystore.jks --ks-pass env:KEY_PASS patched_signed.apk
      
      - name: Publish release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.BUILD_VERSION }}
          files: patched_signed.apk
